-- ============================================================
-- Database Schema
-- PostgreSQL / Tiger Data
--
-- Supabase handles authentication.
-- users.id is the SAME UUID generated by Supabase Auth.
-- ============================================================


-- ============================================================
-- USERS
-- ============================================================

CREATE TABLE users (
    id UUID PRIMARY KEY, -- Supabase Auth UUID

    username VARCHAR(50) UNIQUE NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================
-- USER PREFERENCES
-- One preference profile per user
-- ============================================================

CREATE TABLE user_preferences (
    user_id UUID PRIMARY KEY
        REFERENCES users(id)
        ON DELETE CASCADE,

    diet VARCHAR(100),
    cooking_skill VARCHAR(50),
    servings_default INTEGER DEFAULT 1,
    spice_preference VARCHAR(50),
    budget_preference DECIMAL(10,2),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================
-- ALLERGIES
-- Master list of allergies
-- ============================================================

CREATE TABLE allergies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    name VARCHAR(100) UNIQUE NOT NULL
);


-- ============================================================
-- USER ALLERGIES
-- Many users can have many allergies
-- ============================================================

CREATE TABLE user_allergies (
    user_id UUID NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    allergy_id UUID NOT NULL
        REFERENCES allergies(id)
        ON DELETE CASCADE,

    severity VARCHAR(50),

    PRIMARY KEY (user_id, allergy_id)
);


-- ============================================================
-- FRIENDSHIPS
-- ============================================================

CREATE TABLE friendships (
    user_id UUID NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    friend_id UUID NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    status VARCHAR(20) NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'accepted', 'blocked')),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (user_id, friend_id),

    CHECK (user_id <> friend_id)
);


-- ============================================================
-- RECIPES
-- Imported recipes, generated recipes, manually created recipes
-- ============================================================

CREATE TABLE recipes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    owner_id UUID
        REFERENCES users(id)
        ON DELETE SET NULL,

    title VARCHAR(200) NOT NULL,

    description TEXT,

    -- instagram, tiktok, generated, manual, seeded, etc.
    source VARCHAR(50),

    source_url TEXT,

    image_url TEXT,

    cuisine VARCHAR(100),

    servings INTEGER,

    prep_time_minutes INTEGER,

    cook_time_minutes INTEGER,

    -- Optional estimated cost for the entire recipe
    price_estimate DECIMAL(10,2),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================
-- INGREDIENTS
-- Master ingredient list
-- ============================================================

CREATE TABLE ingredients (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    name VARCHAR(150) UNIQUE NOT NULL,

    category VARCHAR(100)
);


-- ============================================================
-- RECIPE INGREDIENTS
--
-- Connects:
-- recipes <-> ingredients
-- ============================================================

CREATE TABLE recipe_ingredients (
    recipe_id UUID NOT NULL
        REFERENCES recipes(id)
        ON DELETE CASCADE,

    ingredient_id UUID NOT NULL
        REFERENCES ingredients(id)
        ON DELETE RESTRICT,

    quantity DECIMAL(10,2),

    unit VARCHAR(50),

    preparation VARCHAR(200),

    optional BOOLEAN NOT NULL DEFAULT FALSE,

    PRIMARY KEY (recipe_id, ingredient_id)
);


-- ============================================================
-- RECIPE INSTRUCTIONS
-- ============================================================

CREATE TABLE recipe_instructions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    recipe_id UUID NOT NULL
        REFERENCES recipes(id)
        ON DELETE CASCADE,

    step_number INTEGER NOT NULL,

    instruction TEXT NOT NULL,

    UNIQUE (recipe_id, step_number)
);


-- ============================================================
-- RECIPE NUTRITION
-- One nutrition record per recipe
-- Values should represent one serving.
-- ============================================================

CREATE TABLE recipe_nutrition (
    recipe_id UUID PRIMARY KEY
        REFERENCES recipes(id)
        ON DELETE CASCADE,

    calories DECIMAL(10,2),

    protein_grams DECIMAL(10,2),

    carbs_grams DECIMAL(10,2),

    fat_grams DECIMAL(10,2),

    fiber_grams DECIMAL(10,2),

    sugar_grams DECIMAL(10,2),

    sodium_mg DECIMAL(10,2)
);


-- ============================================================
-- PANTRY
-- What a user currently has available
-- ============================================================

CREATE TABLE pantry_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id UUID NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    ingredient_id UUID NOT NULL
        REFERENCES ingredients(id)
        ON DELETE CASCADE,

    quantity DECIMAL(10,2),

    unit VARCHAR(50),

    -- How confident are we that the user still has this?
    -- 0.0 = probably gone
    -- 1.0 = definitely available
    availability_confidence DECIMAL(3,2)
        DEFAULT 1.0
        CHECK (
            availability_confidence >= 0
            AND availability_confidence <= 1
        ),

    last_updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE (user_id, ingredient_id)
);


-- ============================================================
-- SAVED / FAVORITE RECIPES
-- ============================================================

CREATE TABLE saved_recipes (
    user_id UUID NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    recipe_id UUID NOT NULL
        REFERENCES recipes(id)
        ON DELETE CASCADE,

    saved_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (user_id, recipe_id)
);


-- ============================================================
-- RECIPE HISTORY
-- Tracks recipes a user actually cooked
-- ============================================================

CREATE TABLE recipe_history (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id UUID NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    recipe_id UUID NOT NULL
        REFERENCES recipes(id)
        ON DELETE CASCADE,

    cooked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    rating INTEGER
        CHECK (rating >= 1 AND rating <= 5)
);


-- ============================================================
-- RECOMMENDATION SESSIONS
--
-- Represents one recommendation request.
-- Example:
-- "Give me dinner recommendations tonight."
-- ============================================================

CREATE TABLE recommendation_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id UUID NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    user_prompt TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    expires_at TIMESTAMPTZ
);


-- ============================================================
-- RECOMMENDATIONS
--
-- Usually ~3 recipes produced for a session.
-- ============================================================

CREATE TABLE recommendations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    session_id UUID NOT NULL
        REFERENCES recommendation_sessions(id)
        ON DELETE CASCADE,

    recipe_id UUID NOT NULL
        REFERENCES recipes(id)
        ON DELETE CASCADE,

    why_recommended TEXT,

    rank INTEGER,

    saved BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX idx_recipes_owner
    ON recipes(owner_id);


CREATE INDEX idx_recipe_ingredients_recipe
    ON recipe_ingredients(recipe_id);


CREATE INDEX idx_recipe_ingredients_ingredient
    ON recipe_ingredients(ingredient_id);


CREATE INDEX idx_pantry_user
    ON pantry_items(user_id);


CREATE INDEX idx_history_user
    ON recipe_history(user_id);


CREATE INDEX idx_history_recipe
    ON recipe_history(recipe_id);


CREATE INDEX idx_recommendation_sessions_user
    ON recommendation_sessions(user_id);


CREATE INDEX idx_recommendations_session
    ON recommendations(session_id);